### ISSUE TITLE
io.reactivex.exceptions.OnErrorNotImplementedException: Hardware bitmaps are always immutable

### ISSUE THREAD

**Issue by kpradeepkumarreddy** [mayuce/AndroidDocumentScanner#33]
io.reactivex.exceptions.OnErrorNotImplementedException: Hardware bitmaps are always immutable
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:276)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6762)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalArgumentException: Hardware bitmaps are always immutable
        at android.graphics.Bitmap.copy(Bitmap.java:659)
        at com.labters.documentscanner.base.DocumentScanActivity.setImageRotation(DocumentScanActivity.java:64)
        at com.labters.documentscanner.base.DocumentScanActivity.lambda$startCropping$0$DocumentScanActivity(DocumentScanActivity.java:93)
        at com.labters.documentscanner.base.-$$Lambda$DocumentScanActivity$syQvfFNgdVcexd14QWj5Z9g7Jyc.call(Unknown Source:2)
        at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:12030)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by kpradeepkumarreddy** [comment]
I was able to solve this issue by passing a copy of bitmap to ImageCropActivity
`val mutableBitmap: Bitmap = immutableBitmap.copy(Bitmap.Config.ARGB_8888, true)`

I don't know if this is the efficient way to do it. In stackoverflow, it is mentioned that it consumes more memory.
Anybody faced the same issue ?
Any idea why i am getting this exception ?

**Comment by mayuce** [comment]
Maybe we can fix this issue when we show the image as preview but still we'll need to mutate that image I think. There is couple of issues that I needed to deal but I didn't have time to take a look at it. I hope if I can find time next weekend I'll clear them up and this will be top priority. And next one will be moving this repository to maven since jcenter is deprecated.

**Comment by mayuce** [comment]
You can try it out with 1.6.1 version of the library 👍🏻
