### ISSUE TITLE
FATAL EXCEPTION: RxCachedThreadScheduler-1

### ISSUE THREAD

**Issue by Stefan3533** [mayuce/AndroidDocumentScanner#35]
Hi there trying to implement this library into our Android App but it keeps crashing when we try and open the ImageCropActivity.

Our Android App specs:
compileSdkVersion 30
minSdkVersion 21
targetSdkVersion 30
multiDexEnabled true

Kotlin 1.3.50
BuildToolsVersion 29.x
openCVLibrary3412 (Works since we use it for other features in the app)

The actual error message.
```
E/AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-1
    Process: com.avochoc.liquimoly, PID: 16205
    io.reactivex.exceptions.UndeliverableException: java.lang.UnsatisfiedLinkError: No implementation found for void org.opencv.imgproc.Imgproc.resize_3(long, long, double, double) (tried Java_org_opencv_imgproc_Imgproc_resize_13 and Java_org_opencv_imgproc_Imgproc_resize_13__JJDD)
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.UnsatisfiedLinkError: No implementation found for void org.opencv.imgproc.Imgproc.resize_3(long, long, double, double) (tried Java_org_opencv_imgproc_Imgproc_resize_13 and Java_org_opencv_imgproc_Imgproc_resize_13__JJDD)
        at org.opencv.imgproc.Imgproc.resize_3(Native Method)
        at org.opencv.imgproc.Imgproc.resize(Imgproc.java:8627)
        at com.labters.documentscanner.libraries.NativeClass.getPoint(NativeClass.java:68)
        at com.labters.documentscanner.base.DocumentScanActivity.setImageRotation(DocumentScanActivity.java:66)
        at com.labters.documentscanner.base.DocumentScanActivity.lambda$startCropping$0$DocumentScanActivity(DocumentScanActivity.java:93)
        at com.labters.documentscanner.base.-$$Lambda$DocumentScanActivity$syQvfFNgdVcexd14QWj5Z9g7Jyc.call(Unknown Source:2)
        at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:12030)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by mayuce** [comment]
Looks like your open cv module has no function as `resize_3`, issue seems like about version mismatch.

**Comment by mayuce** [comment]
You can try new `1.6.0` version, please check latest readme 👍🏻
